import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const __dirname = dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory: __dirname });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'playwright-report/**',
      'test-results/**',
      // Generated by Next on build.
      'next-env.d.ts',
      // Plain browser script, not part of the TypeScript project.
      'public/**',
    ],
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // The authz chokepoint: application code must not reach for the raw Prisma
    // client for scoped entities. Route reads through lib/authz/scope.ts so
    // vendor isolation cannot be bypassed by a forgotten `where` clause.
    files: ['src/app/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@/lib/db',
              importNames: ['prisma'],
              message:
                'Do not use the raw Prisma client in app code. Use the scoped helpers in @/lib/authz/scope or a service in @/lib/domain so authorization is always applied.',
            },
          ],
        },
      ],
    },
  },
  {
    // Services and the machine surfaces legitimately need the raw client. The
    // SCIM and REST endpoints derive their organization scope from the bearer
    // token rather than from a user's role assignments, so `personScope` does
    // not apply to them — they filter on `organizationId` explicitly.
    files: ['src/lib/**/*.ts', 'src/app/api/**/*.ts', 'src/app/scim/**/*.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },
];

export default config;
